<Project Sdk="Microsoft.NET.Sdk"><!-- TargetFramework, nullability, analyzers and warnings-as-errors: Directory.Build.props -->


  <ItemGroup>
    <PackageReference Include="Anthropic" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mandate.Core\Mandate.Core.csproj" />
  </ItemGroup>
</Project>
