<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Helmsman.Core\Helmsman.Core.csproj" />
    <ProjectReference Include="..\Helmsman.Persistence\Helmsman.Persistence.csproj" />
    <ProjectReference Include="..\Helmsman.Observability\Helmsman.Observability.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>Helmsman.Api</RootNamespace>
  </PropertyGroup>

</Project>
